"""Tests for crypto module — mirrors the TypeScript vitest suite."""

import pytest
from cryptography.hazmat.primitives.ciphers.aead import AESGCM

from venice_e2ee.crypto import (
    decrypt_chunk,
    derive_aes_key,
    encrypt_message,
    from_hex,
    generate_keypair,
    to_hex,
)


class TestHexUtilities:
    def test_roundtrip(self):
        data = bytes([0, 1, 127, 128, 255])
        assert from_hex(to_hex(data)) == data

    def test_empty(self):
        assert to_hex(b"") == ""
        assert from_hex("") == b""

    def test_0x_prefix(self):
        assert from_hex("0xff") == b"\xff"
        assert from_hex("0XAB") == b"\xab"


class TestKeyGeneration:
    def test_generates_valid_keypair(self):
        priv, pub, hex_str = generate_keypair()
        assert len(priv) == 32
        assert len(pub) == 65
        assert pub[0] == 0x04  # uncompressed prefix
        assert hex_str == to_hex(pub)
        assert len(hex_str) == 130  # 65 bytes * 2

    def test_generates_unique_keypairs(self):
        a_priv, a_pub, _ = generate_keypair()
        b_priv, b_pub, _ = generate_keypair()
        assert a_priv != b_priv
        assert a_pub != b_pub


class TestAESKeyDerivation:
    def test_ecdh_symmetry(self):
        """Both sides of ECDH derive identical AES keys."""
        alice_priv, _, alice_hex = generate_keypair()
        bob_priv, _, bob_hex = generate_keypair()

        alice_key = derive_aes_key(alice_priv, bob_hex)
        bob_key = derive_aes_key(bob_priv, alice_hex)

        # Verify by encrypting with one, decrypting with the other
        iv = b"\x00" * 12
        plaintext = b"ECDH symmetry test"
        ct = AESGCM(alice_key).encrypt(iv, plaintext, None)
        pt = AESGCM(bob_key).decrypt(iv, ct, None)
        assert pt == plaintext


class TestEncryptDecryptRoundtrip:
    def test_client_encrypts_server_decrypts(self):
        client_priv, client_pub, client_hex = generate_keypair()
        server_priv, _, server_hex = generate_keypair()

        # Client encrypts with ECDH(client_priv, server_pub)
        client_aes = derive_aes_key(client_priv, server_hex)
        cipher_hex = encrypt_message(client_aes, client_pub, "Hello, Venice TEE!")

        assert len(cipher_hex) > 154  # (65+12)*2 minimum

        # Server decrypts via decryptChunk — extracts embedded client pubkey,
        # does ECDH(server_priv, client_pub) which equals ECDH(client_priv, server_pub)
        decrypted = decrypt_chunk(server_priv, cipher_hex)
        assert decrypted == "Hello, Venice TEE!"

    def test_per_chunk_ephemeral_keys(self):
        """Server response chunks use per-chunk ephemeral keypairs."""
        client_priv, _, client_hex = generate_keypair()

        server_eph_priv, server_eph_pub, server_eph_hex = generate_keypair()
        server_aes = derive_aes_key(server_eph_priv, client_hex)
        cipher_hex = encrypt_message(server_aes, server_eph_pub, "The answer is 42.")

        decrypted = decrypt_chunk(client_priv, cipher_hex)
        assert decrypted == "The answer is 42."

    def test_multiple_chunks_different_ephemeral_keys(self):
        client_priv, _, client_hex = generate_keypair()
        chunks = ["chunk one", "chunk two", "chunk three"]

        for chunk in chunks:
            eph_priv, eph_pub, _ = generate_keypair()
            eph_aes = derive_aes_key(eph_priv, client_hex)
            cipher_hex = encrypt_message(eph_aes, eph_pub, chunk)
            assert decrypt_chunk(client_priv, cipher_hex) == chunk


class TestCrossLanguageCompat:
    """Verify wire-format compatibility with the TypeScript implementation.

    These test vectors were generated by running the TS code with fixed keys
    (private key = 1 for client, private key = 2 for server).
    """

    # secp256k1 public key for private key = 1 (generator point)
    PUB_A_HEX = (
        "0479be667ef9dcbbac55a06295ce870b07029bfcdb2dce28d959f2815b16f81798"
        "483ada7726a3c4655da4fbfc0e1108a8fd17b448a68554199c47d08ffb10d4b8"
    )
    # secp256k1 public key for private key = 2
    PUB_B_HEX = (
        "04c6047f9441ed7d6d3045406e95c07cd85c778e4b8cef3ca7abac09b95c709ee5"
        "1ae168fea63dc339a3c58419466ceaeef7f632653266d0e1236431a950cfe52a"
    )
    # Expected AES key from ECDH(1, pub_2) -> HKDF
    EXPECTED_AES_KEY = "f9c56075758216eed393c6f5b2bff7ef1cdddb796ecdedbef9385f972f89f894"

    def test_ecdh_hkdf_matches_typescript(self):
        """ECDH x-coordinate + HKDF output matches TypeScript noble-secp256k1 + Web Crypto."""
        priv_a = (1).to_bytes(32, "big")
        key = derive_aes_key(priv_a, self.PUB_B_HEX)
        assert to_hex(key) == self.EXPECTED_AES_KEY

    def test_decrypt_typescript_ciphertext(self):
        """Decrypt a ciphertext produced by the TypeScript implementation."""
        # Generated by: TS encryptMessage(deriveAESKey(privB, pubA), pubB, "cross-language test")
        ts_cipher = (
            "04c6047f9441ed7d6d3045406e95c07cd85c778e4b8cef3ca7abac09b95c709ee5"
            "1ae168fea63dc339a3c58419466ceaeef7f632653266d0e1236431a950cfe52a"
            "e855e6be86e048e35e2585ec52bf431cc1bdc1551d8b008d55795a6e2e1151743e"
            "a9e9fdbd9df4787fdc23226c5288"
        )
        priv_a = (1).to_bytes(32, "big")
        assert decrypt_chunk(priv_a, ts_cipher) == "cross-language test"


class TestDecryptChunkPassthrough:
    def test_empty_string(self):
        priv, _, _ = generate_keypair()
        assert decrypt_chunk(priv, "") == ""

    def test_short_string(self):
        priv, _, _ = generate_keypair()
        assert decrypt_chunk(priv, "hello") == "hello"

    def test_whitespace(self):
        priv, _, _ = generate_keypair()
        assert decrypt_chunk(priv, "   ") == "   "

    def test_non_hex(self):
        priv, _, _ = generate_keypair()
        assert decrypt_chunk(priv, "not-hex-data!") == "not-hex-data!"
